module.exports = {
  LANGUAGE_SELECT: 'LANGUAGE_SELECT',
  WELCOME_PANEL: 'WELCOME_PANEL',
  DEMO_INFO_PANEL: 'DEMO_INFO_PANEL',
  COMPARE_PICTURES: 'COMPARE_PICTURES',
  MATCH_FOUND: 'MATCH_FOUND',
  AID_WORKER_CONTACTED: 'AID_WORKER_CONTACTED',
  DEMO_COMPLETE: 'DEMO_COMPLETE',
  FURTHER_INFO: 'FURTHER_INFO',
  ERROR: 'ERROR',
};
