module.exports = {
  LANGUAGE_SELECT: 'LANGUAGE_SELECT',
  WELCOME: 'WELCOME',
  UPLOAD_PIC: 'UPLOAD_PIC',
  SUBMIT_CHOICES: 'SUBMIT_CHOICES',
  SELECT_GENDER: 'SELECT_GENDER',
  SELECT_AGES: 'SELECT_AGES',
  PIC_COMPARISON: 'PIC_COMPARISON',
  FAILURE: 'FAILURE',
  MATCH_FOUND: 'MATCH_FOUND',
};
